### ISSUE TITLE
The terser version of deno-rollup crashes with top level awaits

### ISSUE THREAD

**Issue by eclosson** [crewdevio/Snel#24]
Hello,

I'm trying out snel and when importing a module that contains top level awaits I'm getting the following error:

```
> snel build

.
.
.

SyntaxError: Unexpected await identifier inside strict mode
    at js_error (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:538:11)
    at croak (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:1251:9)
    at token_error (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:1259:9)
    at maybe_unary (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:3223:17)
    at expr_ops (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:3285:24)
    at maybe_conditional (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:3290:20)
    at maybe_assign (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:3367:20)
    at expression (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:3390:24)
    at simple_statement (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:1553:55)
    at statement (https://unpkg.com/terser@5.3.1/dist/bundle.min.js:1366:19)
```

I tracked this down to the deno-rollup project and got a fixed merged into the origin project here: https://github.com/cmorten/deno-rollup/issues/41

I see snel actually has a dependency on `https://denopkg.com/buttercubz/deno-rollup@improve-perfomance` and that the `improve-performance` branch has deviated from the origin project.

I'd like to get that patch in the origin project into the snel dependency.

I'm happy to work on it but could use some guidance wrt `buttercubz/deno-rollup@improve-perfomance` and the direction to take.

**Comment by buttercubz** [comment]
Hello, thanks for the observation, the current version of [rollup](https://github.com/buttercubz/deno-rollup/tree/improve-perfomance) contains some changes that improve the speed of recompiling and hotreloading, those changes were already [suggested in drollup](https://github.com/cmorten/deno-rollup/pull/38) and they are being reviewed, since they are approved I will release an update. in the same way I could update the current version to solve these problems

**Comment by eclosson** [comment]
Great, thank you!

**Comment by buttercubz** [comment]
> Great, thank you!

@eclosson [deno-rollup@improve-perfomance](https://github.com/buttercubz/deno-rollup/tree/improve-perfomance) is already update with deno rollup, you can install again using -r and -f flag and try again

**Comment by buttercubz** [comment]
i can confirm that is resolved, but only in `js/ts` files svelte compiler not support `TLA` but with an `IIFE` can resolve it
