### ISSUE TITLE
Example app fails to build due to css processing error

### ISSUE THREAD

**Issue by arctica** [crewdevio/Snel#56]
When creating an example app via `snel create myapp` and then running `trex run build` it will fail with the follow output:

```
$ trex run build
preparing files for production.

Entry public/__index.html
Error: public/global.css: R.default.comma is not a function
    at CssPlugin.createAsset (https://deno.land/x/deno_bundler@v0.9.1/plugins/css/css.ts:87:13)
    at async Bundler.createAsset (https://deno.land/x/deno_bundler@v0.9.1/bundler.ts:155:23)
    at async Bundler.createGraph (https://deno.land/x/deno_bundler@v0.9.1/bundler.ts:251:17)
    at async Bundler.bundle (https://deno.land/x/deno_bundler@v0.9.1/bundler.ts:621:19)
    at async Dist (https://deno.land/x/snel@v0.7.1/src/cli/prepare.ts:54:23)
    at async Build (https://deno.land/x/snel@v0.7.1/src/cli/commands/build.ts:33:5)
    at async Object.build (https://deno.land/x/snel@v0.7.1/cli.ts:52:42)
    at async Main (https://deno.land/x/snel@v0.7.1/cli.ts:99:14)
    at async https://deno.land/x/snel@v0.7.1/cli.ts:138:3
```

I narrowed it down to the following css rule, the parens seem to be the issue.

```css
button:not(:disabled):active {
  background-color: #ddd;
}
```

This is probably a bug in "Deno Bundler" but that github repo does not have issues enabled and the original that it was forked from seems to not be maintained anymore. I'm not sure what can be done in this case. Are there maybe alternatives to "Deno Bundler"?

**Comment by buttercubz** [comment]
#61
