### ISSUE TITLE
Unable to install snel with install.ts

### ISSUE THREAD

**Issue by jmherbst** [crewdevio/Snel#57]
Running on my m1 mac:
```
» deno --version
deno 1.22.0 (release, aarch64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2
```

Install failure log
```javascript
» deno run --allow-run --allow-read -r https://deno.land/x/snel/install.ts
Download https://deno.land/x/snel/install.ts
Warning Implicitly using latest version (v0.7.1) for https://deno.land/x/snel/install.ts
Download https://deno.land/x/snel@v0.7.1/install.ts
Download https://cdn.skypack.dev/svelte@3.46.4/animate
Download https://cdn.skypack.dev/svelte@3.46.4/easing
Download https://cdn.skypack.dev/svelte@3.46.4/internal
Download https://cdn.skypack.dev/svelte@3.46.4/motion
Download https://cdn.skypack.dev/svelte@3.46.4/store
Download https://cdn.skypack.dev/svelte@3.46.4/transition
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/transition.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/motion.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/animate.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/easing.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/internal.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/svelte/store.js
Download https://cdn.skypack.dev/-/svelte@v3.46.4-xym63myK8b1EihujDDAL/dist=es2019,mode=imports/optimized/common/global-5c50bad9.js
Check https://deno.land/x/snel/install.ts
Warning Implicitly using latest version (v0.7.1) for https://deno.land/x/snel/cli.ts
error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24
Warning Implicitly using latest version (v1.11.0) for https://deno.land/x/trex/import_map.json
Warning Implicitly using latest version (v1.11.0) for https://deno.land/x/trex/cli.ts
Warning Implicitly using latest version (v1.11.0) for https://deno.land/x/trex/utils/types.ts
Warning Implicitly using latest version (0.140.0) for https://deno.land/std/fmt/colors.ts
✅ Successfully installed trex
/Users/j/.deno/bin/trex
installation complete.
```

Snel + Trex attempt:
```zsh
» export PATH="/Users/j/.deno/bin:$PATH"

» snel
zsh: command not found: snel

» trex exec snel create name
error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24
error: Uncaught (in promise) something went wrong while running snel

```

Any suggestions?

**Comment by buttercubz** [comment]
Hi @jmherbst currently snel is broken as deno-rollup is also broken due to a change made in deno's namespace but I'm already working on a hot fix

**Comment by ThamizharasaN2116** [comment]
Hi @buttercubz , 
Is there any workaround or we have to wait till we get the fix?
Thanks.

**Comment by Rin-Akaia-eth** [comment]
Same problem here.

**Comment by delight** [comment]
I'd really love to try this but as it seems right now there is not way to get this started.

Got a question though: are there any plans to make snel work with [fresh](https://fresh.deno.dev/) ?  Would be awesome and something to look forward to.

**Comment by nberlette** [comment]
@buttercubz any update on the status of this? I'm sure I'm only one of ***many*** users who are really bummed about snel being dead in the water all this time :(

**Comment by buttercubz** [comment]
Hello, this is an update, I have been a bit busy with my work, but I want to inform you that an update will be coming which will solve all the current errors of snel, also now it will use vite as main engine, features like typescript, less, scss and import maps out the box will be progressively available again.

@jmherbst @ThamizharasaN2116 @delight @nberlette

**Comment by buttercubz** [comment]
#61 pull request

**Comment by buttercubz** [comment]
@delight @jmherbst @ThamizharasaN2116 @nberlette https://github.com/crewdevio/Snel/issues/62#issuecomment-1913681240
