### ISSUE TITLE
Snel install fails on windows

### ISSUE THREAD

**Issue by dekelly** [crewdevio/Snel#62]
Trying to install snel on my windows machine getting following failure -

S C:\> deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24
installation complete.

PS C:\> deno --version
deno 1.31.1 (release, x86_64-pc-windows-msvc)
v8 11.0.226.13
typescript 4.9.4

**Comment by buttercubz** [comment]
> Trying to install snel on my windows machine getting following failure -
> 
> S C:> deno run --allow-run --allow-read https://deno.land/x/snel/install.ts error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts". at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24 installation complete.
> 
> PS C:> deno --version deno 1.31.1 (release, x86_64-pc-windows-msvc) v8 11.0.226.13 typescript 4.9.4

@dekelly please try this:

```console
deno install -A -n snel https://raw.githubusercontent.com/crewdevio/Snel/main/cli.ts
```

this one now use vite under the hood
